using EulerMonocle;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EulersMonocle
{
    class Even_Fibonacci_numbers : IProblem
    {
        public const Int16 PROBLEM_NUMBER = 2;
        public Int16 GetProblemNumber()
        {
            return PROBLEM_NUMBER;
        }

        public Solution GetSolution()
        {
            var result =
                new Solution()
                {
                    ProblemNumber = PROBLEM_NUMBER,
                    ProblemText = GetProblemText(),
                    Result = GetResult()
                };

            return result;
        }

        private string GetResult()
        {
            Int32 first = 1;
            Int32 second = 2;
            Int32 third = 3;

            Int32 sum = 0;
            while (first < 4000000)
            {
                checked
                {
                    if (first % 2 == 0) sum += first;
                }
                var newThird = second + third;
                first = second;
                second = third;
                third = newThird;
            }

            return sum.ToString();
        }

        private String GetProblemText()
        {
            return
                "Each new term in the Fibonacci sequence is" +
                " generated by adding the previous two terms." +
                " By starting with 1 and 2, the first 10 terms" +
                " will be [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]." +
                " By considering the terms in the Fibonacci" +
                " sequence whose values do not exceed four" +
                " million, find the sum of the even-valued terms.";
        }
    }
}
